volumes:
  db:
  redis:
  assets:
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    tty: true
  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: "api"
    env_file:
      - ./.env
    build:
      context: ./
    ports: 
      - ${PORT}:${PORT}
    links:
      - postgres
      - redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./assets:/app/assets
  migration:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./
      dockerfile: ./prisma/Dockerfile
    command: ./wait-for-it/wait-for-it.sh postgres:5432 -- npm run migrate-deploy && npm seed;
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - ./.env
    
  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  redis-commander:
    container_name: commander
    image: rediscommander/redis-commander
    restart: always
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
  worker:
    extra_hosts:
        - "host.docker.internal:host-gateway"
    build:
      context: ./server/redis
    depends_on:
      - redis
      - postgres
    stdin_open: true
    tty: true
    volumes:
      - ./server/redis/worker.py:/app/worker.py
    deploy:
      mode: replicated
      replicas: 2
    links:
      - redis
      - postgres
    env_file:
      - ./.env
  client:
    container_name: "client"
    build:
      context: ./client
    ports: 
      - ${CLIENT_PORT}:4173
  
