volumes:
  db:
services:
  db:
    image: postgres
    container_name: "database"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: ./client/dist/
      dockerfile: ./Dockerfile
    container_name: "client"
    ports: 
      - 8100:8100
    develop: 
      watch: 
      - action: rebuild
      - path: .
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: "server"
    develop: 
      watch: 
      - action: rebuild
      - path: .
    ports: 
      - 3000:3000
  
